import uuid
from datetime import UTC, datetime

from src.domain.models.recommendation import RecommendationLog
from src.infrastructure.database.models import Recommendation


def test_recommendation_model_creation() -> None:
    rec = Recommendation(
        prompt="Test Prompt",
        recommendations={"test": "data"},
        model="test-model",
        response_time=0.5,
        status="success",
    )
    assert rec.prompt == "Test Prompt"
    assert rec.recommendations == {"test": "data"}
    assert rec.model == "test-model"
    assert rec.response_time == 0.5
    assert rec.status == "success"
    # id and created_at are generated by DB session usually, but we can check they are absent until commit, or check model fields.


def test_recommendation_log_dto_creation() -> None:
    dt = datetime.now(UTC)
    uid = uuid.uuid4()
    log = RecommendationLog(
        prompt="Hello",
        response="{}",
        model="gemini",
        response_time=1.0,
        status="success",
        id=uid,
        created_at=dt,
    )
    assert log.prompt == "Hello"
    assert log.id == uid
    assert log.created_at == dt
